<?php


/**
 * @file Enables Views to leverage menu hierarchies when displaying nodes.
 */
module_load_include('inc', 'menu_node_views', 'menu_node_views.views');
/**
 * Implement hook_views_api().
 */
function menu_node_views_views_api() {
  return array('api' => 2.0);
}

/**
 * Implements hook_autoload_info().
 */
function menu_node_views_autoload_info() {
  return array(
    'menu_node_views_argument_nid' => 'includes/menu_node_views_argument_nid.inc',
    'menu_node_views_field_link_title' => 'includes/menu_node_views_field_link_title.inc',
    'menu_node_views_sort_menu' => 'includes/menu_node_views_sort_menu.inc',
    'menu_node_views_field_description' => 'includes/menu_node_views_field_description.inc',
    'menu_node_views_field_menu_name' => 'includes/menu_node_views_field_menu_name.inc',
  );
}
